name: Style check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-cache-${{ runner.os }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            uv-cache-${{ runner.os }}-

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
        
      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv pip sync --system pyproject.toml --extra dev

      - name: Check linting with Ruff
        run: ruff check

      - name: Check format with Ruff
        run: ruff format --check

      - name: Check docstring coverage
        run: docstr-coverage ./**/*.py --fail-under 20 --verbose=2 --skip-file-doc --skip-init
